=== gknowles/gw1builds/data/other/gwdata1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="GWData">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Region" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="SkillBar">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Skill" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:token" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Item">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="type" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="wand"/>
            <xs:enumeration value="focus"/>
            <xs:enumeration value="staff"/>
            <xs:enumeration value="bow"/>
            <xs:enumeration value="axe"/>
            <xs:enumeration value="hammer"/>
            <xs:enumeration value="sword"/>
            <xs:enumeration value="shield"/>
            <xs:enumeration value="daggers"/>
            <xs:enumeration value="scythe"/>
            <xs:enumeration value="spear"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Region">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Zone" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="Boss" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element ref="Trainer" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:token" use="required"/>
            <xs:attribute name="type" default="area">
              <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                  <xs:enumeration value="area"/>
                  <xs:enumeration value="city"/>
                  <xs:enumeration value="outpost"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element ref="SkillBar" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:token" use="required"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="Boss">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SkillBar" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:token" use="required"/>
      <xs:attribute name="profession" type="profession"/>
      <xs:attribute name="species" type="xs:string"/>
      <xs:attribute name="quest" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Trainer">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Skill" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:token" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Quest">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Skill" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="Item" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="zone" type="xs:string" use="required"/>
      <xs:attribute name="npc" type="xs:string" use="required"/>
      <xs:attribute name="profession" type="profession" use="optional">
        <xs:annotation><xs:documentation>
          Profession required to activate quest, if not present any profession can activate it  
        </xs:documentation></xs:annotation>
      </xs:attribute>
      <xs:attribute name="prereq" type="xs:string" use="optional">
        <xs:annotation><xs:documentation>
          Quest that must be taken before this one can be activated  
        </xs:documentation></xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gknowles/gw1builds/data/other/region-southern-shiverpeaks.xml
<?xml version="1.0"?>
<Region xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="gwdata1.xsd"
 name="Southern Shiverpeaks">
  <Zone name="Camp Rankor" type="outpost">
    <Trainer name="Steig">
      <Skill>Conjure Lightning</Skill>
      <Skill>Glyph of Concentration</Skill>
      <Skill>Glyph of Sacrifice</Skill>
      <Skill>Mantra of Inscriptions</Skill>
      <Skill>Signet of Weariness</Skill>
      <Skill>Convert Hexes</Skill>
      <Skill>Barbs</Skill>
      <Skill>Consume Corpse</Skill>
      <Skill>Nature's Renewal</Skill>
      <Skill>Symbiotic Bond</Skill>
    </Trainer>
  </Zone>
  <Zone name="Copperhammer Mines" type="outpost">
    <Trainer name="Gammel">
      <Skill>Signet of Capture</Skill>
      <Skill>Mark of Rodgort</Skill>
      <Skill>Searing Heat</Skill>
      <Skill>Clumsiness</Skill>
      <Skill>Mantra of Signets</Skill>
      <Skill>Divine Intervention</Skill>
      <Skill>Draw Conditions</Skill>
      <Skill>Scourge Sacrifice</Skill>
      <Skill>Verata's Aura</Skill>
      <Skill>Verata's Gaze</Skill>
      <Skill>Verata's Sacrifice</Skill>
      <Skill>Muddy Terrain</Skill>
      <Skill>Primal Echoes</Skill>
      <Skill>Riposte</Skill>
      <Skill>Rush</Skill>
    </Trainer>
  </Zone>
  <Zone name="Deldrimor War Camp" type="outpost"/>
  <Zone name="Grenth's Footprint">
    <Boss name="Gargash Thornbeard" profession="R" species="Dwarf">
    </Boss>
    <Boss name="Gorrel Rockmolder" profession="Me" species="Dwarf">
      <Item name="The Rockmolder" type="focus"/>
    </Boss>
    <Boss name="Flint Fleshcleaver" profession="E" species="Ice Golem">
      <!-- Water Trident -->
    </Boss>
    <Boss name="Thorgall Bludgeonhammer" profession="W" species="Dwarf">
      <Item name="Thorgall's Shield" type="shield"/>
    </Boss>
  </Zone>
  <Zone name="Droknar's Forge" type="city">
    <Trainer name="Bartoch">
      <Skill>Signet of Capture</Skill>
      <Skill>Deep Freeze</Skill>
      <Skill>Earthquake</Skill>
      <Skill>Fire Attunement</Skill>
      <Skill>Flame Burst</Skill>
      <Skill>Incendiary Bonds</Skill>
      <Skill>Obsidian Flame</Skill>
      <Skill>Swirling Aura</Skill>
      <Skill>Windborne Speed</Skill>
      <Skill>Arcane Conundrum</Skill>
      <Skill>Blackout</Skill>
      <Skill>Elemental Resistance</Skill>
      <Skill>Ether Lord</Skill>
      <Skill>Guilt</Skill>
      <Skill>Mantra of Earth</Skill>
      <Skill>Mantra of Persistence</Skill>
      <Skill>Mind Wrack</Skill>
      <Skill>Balthazar's Aura</Skill>
      <Skill>Blessed Aura</Skill>
      <Skill>Blessed Signet</Skill>
      <Skill>Healing Touch</Skill>
      <Skill>Mend Condition</Skill>
      <Skill>Scourge Healing</Skill>
      <Skill>Vengeance</Skill>
      <Skill>Zealot's Fire</Skill>
      <Skill>Animate Bone Fiend</Skill>
      <Skill>Animate Bone Minions</Skill>
      <Skill>Chilblains</Skill>
      <Skill>Demonic Flesh</Skill>
      <Skill>Malaise</Skill>
      <Skill>Price of Failure</Skill>
      <Skill>Signet of Agony</Skill>
      <Skill>Well of the Profane</Skill>
      <Skill>Choking Gas</Skill>
      <Skill>Concussion Shot</Skill>
      <Skill>Dust Trap</Skill>
      <Skill>Edge of Extinction</Skill>
      <Skill>Flame Trap</Skill>
      <Skill>Precision Shot</Skill>
      <Skill>Tiger's Fury</Skill>
      <Skill>Winnowing</Skill>
      <Skill>Fear Me!</Skill>
      <Skill>Shields Up!</Skill>
      <Skill>To the Limit!</Skill>
      <Skill>Balanced Stance</Skill>
      <Skill>Bull's Strike</Skill>
      <Skill>Defensive Stance</Skill>
      <Skill>Savage Slash</Skill>
      <Skill>Shield Bash</Skill>
    </Trainer>
  </Zone>
  <Zone name="The Granite Citadel" type="outpost"/>
  <Zone name="Marhan's Grotto" type="outpost">
    <Trainer name="Harnil">
      <Skill>Signet of Capture</Skill>
      <Skill>Aftershock</Skill>
      <Skill>Rodgort's Invocation</Skill>
      <Skill>Mantra of Resolve</Skill>
      <Skill>Soothing Images</Skill>
      <Skill>Light of Dwayna</Skill>
      <Skill>Dark Fury</Skill>
      <Skill>Desecrate Enchantments</Skill>
      <Skill>Dryder's Defenses</Skill>
      <Skill>Frozen Soil</Skill>
      <Skill>Symbiosis</Skill>
      <Skill>Crude Swing</Skill>
      <Skill>Warrior's Cunning</Skill>
    </Trainer>
  </Zone>
  <Zone name="Port Sledge" type="outpost">
    <Trainer name="Thengen">
      <Skill>Signet of Capture</Skill>
      <Skill>Glyph of Elemental Power</Skill>
      <Skill>Rust</Skill>
      <Skill>Ignorance</Skill>
      <Skill>Mantra of Lightning</Skill>
      <Skill>Divine Healing</Skill>
      <Skill>Infuse Condition</Skill>
      <Skill>Order of Pain</Skill>
      <Skill>Disrupting Lunge</Skill>
      <Skill>Energizing Wind</Skill>
      <Skill>Berserker Stance</Skill>
      <Skill>Deflect Arrows</Skill>
    </Trainer>
  </Zone>

  <Zone name="Sorrow's Furnace">
    <Boss name="Brohn Stoneheart" profession="Mo" species="Dwarf">
    </Boss>
    <Boss name="Drago Stoneherder" profession="R" species="Dwarf">
    </Boss>
    <Boss name="Galigord Stonestrike" profession="E" species="Dwarf">
      <SkillBar>Furnace Elementalist</SkillBar>
    </Boss>
    <Boss name="Garbok Handsmasher" profession="Me" species="Dwarf">
      <SkillBar>Furnace Mesmer</SkillBar>
    </Boss>
    <Boss name="Gardock Stonesoul" profession="Mo" species="Dwarf">
      <SkillBar>Furnace Monk</SkillBar>
    </Boss>
    <Boss name="Gordak Fleshweaver" profession="N" species="Dwarf">
    </Boss>
    <Boss name="Grognard Gravelhead" profession="W" species="Dwarf">
    </Boss>
    <Boss name="Runar Brimstone" profession="E" species="Dwarf">
      <SkillBar>Furnace Elementalist</SkillBar>
    </Boss>
    <Boss name="Tanzit Razorstone" profession="W" species="Dwarf">
    </Boss>
    <Boss name="Tarnok Forgerunner" profession="R" species="Dwarf">
    </Boss>
    <Boss name="Villnar Painforge" profession="N" species="Dwarf">
    </Boss>
    <Boss name="Vokur Grimshackles" profession="Me" species="Dwarf">
      <SkillBar>Furnace Mesmer</SkillBar>
    </Boss>
  </Zone>

  <SkillBar name="Furnace Elementalist">
    <Skill>Earth Attunement</Skill>
    <Skill>Obsidian Flame</Skill>
    <Skill>Stoning</Skill>
    <Skill>Rust</Skill>
  </SkillBar>
  <SkillBar name="Furnace Mesmer">
    <Skill>Crippling Anguish</Skill>
  </SkillBar>
  <SkillBar name="Furnace Monk">
    <Skill>Mark of Protection</Skill>
  </SkillBar>
</Region>
